/**
 * 🎯 INSIGHTS PANEL - VERSION FINALE (FIX ARGUMENTS UPDATE)
 */
import { memo, useCallback } from 'react';
import { useGlobalIntelligence } from '../hooks/use-global-intelligence';
import { ProjectionCard } from '@/features/predictions/components/ProjectionCard';
import { RecurringCard } from '@/features/recurring/components/RecurringCard';
import { ViolationsCard } from '@/features/intelligence/components/ViolationsCard';
import { AnomaliesCard } from '@/features/analytics/components/AnomaliesCard'; 
import { SectionWrapper } from './SectionWrapper';
import { LoadingState } from './LoadingState';
import { TrendingUp, Sparkles, ShieldAlert } from 'lucide-react';
import { useData } from '@/contexts/DataContext'; 
import { toast } from 'sonner';
import type { Transaction } from '@/features/transactions/types';
import type { RecurringPattern } from '@/features/recurring/engine/recurring-detection';
import { PersonType } from '@/features/people/types/base';

export const InsightsPanel = memo(function InsightsPanel({ 
  onFilterByTransaction, 
  onFilterByRecurring,
  onFilterByAnomaly,
  onShowProjectionDetails,
  transactions: externalTransactions
}: any) {
  
  const { projection, recurring, alerts, isSyncing, isEmpty, transactions: internalTransactions } = useGlobalIntelligence();
  
  // ✅ On récupère updateTransaction (SANS LE S) du DataContext
  const { people, updatePeople, updateTransaction } = useData();

  const activeTransactions = externalTransactions || internalTransactions || [];

  const handleLinkPattern = useCallback(async (pattern: RecurringPattern) => {
    // ✅ Vérification de la présence de updateTransaction
    if (!updatePeople || !updateTransaction) return;

    const firstTx = pattern.transactions[0];
    const patternName = firstTx?.description || "Nouveau Prestataire";
    const patternAmount = pattern.averageAmount || firstTx?.amount || 0;

    const personId = `rel_${Date.now()}`;

    const newPerson: any = {
      id: personId,
      name: patternName,
      personType: PersonType.MORALE,
      category: pattern.category || 'Abonnement',
      totalImpact: patternAmount, 
      metadata: { isAutoGenerated: true, linkedPatternId: pattern.id },
      transactionsCount: pattern.transactions.length,
      lastTransactionDate: new Date().toISOString()
    };

    try {
      await updatePeople([...people, newPerson]);

      // ✅ Utilisation de updateTransaction (singulier) qui accepte (id, updates)
      for (const tx of pattern.transactions) {
        await updateTransaction(tx.id, { personId: personId });
      }
      
      toast.success(`${patternName} ajouté aux relations`);
    } catch (error) {
      console.error("❌ Erreur liaison:", error);
      toast.error("Erreur lors de la liaison");
    }
  }, [people, updatePeople, updateTransaction]);

  if (isSyncing) return <LoadingState />;
  if (isEmpty && activeTransactions.length === 0) {
    return <div className="p-8 text-center text-white/20 text-xs">Aucune donnée à analyser</div>;
  }

  return (
    <div className="flex flex-col gap-8 p-4 custom-scrollbar overflow-y-auto h-full">
      <SectionWrapper title="Fin de mois" icon={TrendingUp} color="text-cyan-400">
        {projection ? (
          <ProjectionCard 
            projection={projection} 
            transactions={activeTransactions}
            onShowDetails={() => onShowProjectionDetails?.(projection)}
          />
        ) : (
          <div className="p-4 rounded-xl border border-white/5 bg-white/[0.01] text-[10px] text-white/20 text-center">
            Analyse du solde en cours...
          </div>
        )}
      </SectionWrapper>

      <SectionWrapper title="Abonnements" icon={Sparkles} color="text-purple-400">
        <RecurringCard 
          recurring={recurring}
          existingPeople={people}
          onFilterByRecurring={onFilterByRecurring}
          onCreateRelation={handleLinkPattern}
        />
      </SectionWrapper>

      <SectionWrapper title="Sécurité & IA" icon={ShieldAlert} color="text-orange-400">
        <div className="space-y-4">
          <ViolationsCard onFilterByTransaction={onFilterByTransaction} />
          {alerts?.violations && alerts.violations.length > 0 && (
            <AnomaliesCard 
              anomalies={alerts.violations} 
              onSelectTransaction={(tx: Transaction) => onFilterByTransaction?.(tx.id)}
              onFilterByAnomaly={(val) => onFilterByAnomaly?.(val)} 
            />
          )}
        </div>
      </SectionWrapper>
    </div>
  );
});