/**
 * 🎯 LEFT PANEL INSIGHTS - VERSION INTÉGRÉE & COMPLÈTE 2026
 * 
 * Logiciel de gestion :
 * - Utilise DataContext pour People et Transactions
 * - Orchestre la création de relations via handleCreateRelationFromPattern
 * - Préserve l'intégralité du design system et des logiques de filtrage
 */

import { useState, useEffect, useMemo, memo, startTransition, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sparkles,
  TrendingUp,
  Calendar,
  AlertTriangle,
  Layers,
  ChevronRight
} from 'lucide-react';

// Contextes
import { useData, Transaction } from 'contexts/DataContext';
import { useRules } from 'contexts/RulesContext';
import { useTransactionSettings } from 'contexts/TransactionSettingsContext';

// Hooks & Utils
import { calculateMonthEndProjection } from 'src/utils/insights/projection';
import { detectAnomalies } from 'src/utils/insights/anomaly-detection';
import { detectRecurringPatterns, RecurringPattern } from 'src/utils/insights/recurring-detection';
import { parseTransactionDescription } from 'src/utils/transaction-parser';
import { useRuleViolationsCache } from '@/hooks/useRuleViolationsCache';
import { useRecentTransactions } from '@/hooks/useRecentTransactions';
import { useDebouncedValue } from '@/hooks/useDebouncedValue';

// Composants Cards
import { ProjectionCard } from './cards/ProjectionCard';
import { RecurringCard } from './cards/RecurringCard';
import { AnomaliesCard } from './cards/AnomaliesCard';
import { ViolationsCard } from './cards/ViolationsCard';
import { ProjectionDetailsModal } from './ProjectionDetailsModal';

interface LeftPanelInsightsProps {
  transactions: Transaction[];
  currentBalance: number;
  onFilterByTransaction?: (transactionId: string) => void;
  onFilterByAnomaly?: (description: string) => void;
  onFilterByRecurring?: (transactionIds: string[]) => void;
  onToggle?: () => void;
}

type ViewMode = 'all' | 'projection' | 'recurring' | 'alerts';

const InsightSkeleton = () => (
  <div className="rounded-xl bg-white/5 border border-white/10 p-5 space-y-3 animate-pulse">
    <div className="flex items-center gap-3">
      <div className="w-8 h-8 rounded-lg bg-white/10" />
      <div className="flex-1 space-y-2">
        <div className="h-3 bg-white/10 rounded w-1/3" />
        <div className="h-2 bg-white/10 rounded w-1/2" />
      </div>
    </div>
    <div className="space-y-2 pt-3">
      <div className="h-2 bg-white/10 rounded" />
      <div className="h-2 bg-white/10 rounded w-5/6" />
    </div>
  </div>
);

export const LeftPanelInsights = memo(function LeftPanelInsights({
  transactions,
  currentBalance,
  onFilterByTransaction,
  onFilterByAnomaly,
  onFilterByRecurring,
  onToggle,
}: LeftPanelInsightsProps) {
  // États
  const [viewMode, setViewMode] = useState<ViewMode>('all');
  const [projectionData, setProjectionData] = useState<any>(null);
  const [anomaliesData, setAnomaliesData] = useState<any>(null);
  const [recurringData, setRecurringData] = useState<any>(null);
  const [violationsLoaded, setViolationsLoaded] = useState(false);
  const [showProjectionDetails, setShowProjectionDetails] = useState(false);

  // Data & Settings Contexts
  const { rules } = useRules();
  const { settings } = useTransactionSettings();
  const { people, updatePeople, updateTransactions } = useData();

  // Performance : Debounce & Hooks
  const debouncedTransactions = useDebouncedValue(transactions, 800);
  const { recent: recentTransactions } = useRecentTransactions(debouncedTransactions, 6);
  const ruleViolations = useRuleViolationsCache(rules, violationsLoaded ? recentTransactions : []);

  /**
   * 🛠 LOGIQUE MÉTIER : CRÉATION DE RELATION
   * Orchestre la création d'une relation et lie les transactions existantes.
   */
  const handleCreateRelationFromPattern = useCallback((pattern: RecurringPattern) => {
    const parsed = parseTransactionDescription(pattern.description);
    
    // 1. Création de la nouvelle personne/relation
    const newPerson = {
      id: crypto.randomUUID(),
      name: parsed.merchant,
      relationship: 'Abonnement IA',
      color: parsed.color || 'purple',
      circle: 'Professionnel',
      totalImpact: Math.abs(pattern.averageAmount),
      isAutoGenerated: true
    };

    // 2. Mise à jour du context People
    const updatedPeople = [...people, newPerson];
    updatePeople(updatedPeople);

    // 3. Liaison des transactions dans le DataContext
    const patternTxIds = new Set(pattern.transactions.map(t => t.id));
    const updatedTransactions = transactions.map(tx => {
      if (patternTxIds.has(tx.id)) {
        return { ...tx, personId: newPerson.id, category: parsed.category };
      }
      return tx;
    });

    updateTransactions(updatedTransactions);
  }, [people, transactions, updatePeople, updateTransactions]);

  // Calculs asynchrones étagés
  useEffect(() => {
    if (recentTransactions.length === 0) return;
    let cancelled = false;
    const timers: NodeJS.Timeout[] = [];

    const compute = () => {
      timers.push(setTimeout(() => {
        if (cancelled) return;
        const projection = calculateMonthEndProjection(recentTransactions, currentBalance, {
          inflationFactor: settings.projection?.inflationFactor,
          userAge: settings.projection?.userAge,
        });
        startTransition(() => setProjectionData(projection));
      }, 0));

      timers.push(setTimeout(() => {
        if (cancelled) return;
        if (!settings.anomaly?.enabled) {
          setAnomaliesData({ anomalies: [], suspiciousCount: 0 });
          return;
        }
        const anomalies = detectAnomalies(recentTransactions, settings.anomaly);
        startTransition(() => setAnomaliesData(anomalies));
      }, 300));

      timers.push(setTimeout(() => {
        if (cancelled) return;
        if (!settings.recurring?.enabled) {
          setRecurringData({ patterns: [], totalRecurringTransactions: 0, monthlyRecurringAmount: 0 });
          return;
        }
        
        // 1️⃣ Détection brute des patterns
        const recurring = detectRecurringPatterns(recentTransactions, settings.recurring);
        
        // 2️⃣ 🔑 ENRICHISSEMENT CRUCIAL : Réconciliation avec les relations existantes
        // Pour chaque pattern, on cherche si ses transactions ont déjà un personId
        // Si oui, on récupère le nom ACTUEL de la relation (ex: "My Astuce")
        const enrichedPatterns = recurring.patterns.map((pattern: RecurringPattern) => {
          // Cherche la première transaction du pattern qui a un personId
          const firstLinkedTx = pattern.transactions.find(t => t.personId);
          
          if (firstLinkedTx && firstLinkedTx.personId) {
            // Récupère l'objet PersonRelation correspondant
            const existingPerson = people.find(p => p.id === firstLinkedTx.personId);
            
            if (existingPerson) {
              // ✨ MAGIE : On remplace la description brute par le nom de la relation
              return {
                ...pattern,
                displayName: existingPerson.name, // "My Astuce" au lieu de "TransDev"
                linkedPersonId: existingPerson.id,
                linkedPersonName: existingPerson.name,
                isAlreadyLinked: true,
                // On garde la description originale pour le fallback
                originalDescription: pattern.description
              };
            }
          }
          
          // Pattern non lié : on garde la description brute
          return {
            ...pattern,
            displayName: pattern.description,
            linkedPersonId: null,
            linkedPersonName: null,
            isAlreadyLinked: false,
            originalDescription: pattern.description
          };
        });
        
        startTransition(() => setRecurringData({
          ...recurring,
          patterns: enrichedPatterns
        }));
      }, 800));

      timers.push(setTimeout(() => {
        if (cancelled) return;
        setViolationsLoaded(true);
      }, 1200));
    };

    compute();
    return () => { cancelled = true; timers.forEach(clearTimeout); };
  }, [recentTransactions, currentBalance, settings, people]); // 🔑 Ajout de 'people' pour re-calculer si les noms changent
  
  const alertsCount = (anomaliesData?.suspiciousCount || 0) + ruleViolations.length;
  const recurringCount = recurringData?.patterns.filter((p: any) => p.isActive).length || 0;

  if (showProjectionDetails && projectionData) {
    return (
      <div className="h-full flex flex-col bg-black border-r border-white/10 w-[360px]">
        <ProjectionDetailsModal
          projection={projectionData}
          transactions={recentTransactions}
          currentBalance={currentBalance}
          onClose={() => setShowProjectionDetails(false)}
          onFilterByTransaction={onFilterByTransaction}
          onFilterByRecurring={onFilterByRecurring}
        />
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-black border-r border-white/10 w-[360px]">
      
      {/* HERO SECTION */}
      <div className="relative overflow-hidden border-b border-white/10">
        <div className="absolute top-0 right-0 w-40 h-40 bg-cyan-500/20 rounded-full blur-3xl" />
        <div className="relative p-4">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2.5">
              <motion.button
                onClick={onToggle}
                className="w-8 h-8 rounded-xl bg-gradient-to-br from-cyan-500/20 to-purple-500/20 border border-cyan-500/30 flex items-center justify-center shadow-[0_0_20px_rgba(6,182,212,0.15)] cursor-pointer hover:scale-105"
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                <Sparkles className="w-4 h-4 text-cyan-400" />
              </motion.button>
              <div>
                <h2 className="text-sm text-white font-medium">Insights IA</h2>
                <p className="text-xs text-white/40">Analyse en temps réel</p>
              </div>
            </div>
          </div>
          
          {/* NAV TABS */}
          <div className="flex items-center gap-2">
            {[
              { id: 'all', label: 'Vue globale', icon: Layers, color: 'cyan' },
              { id: 'projection', label: 'Projection', icon: TrendingUp, color: 'blue', badge: projectionData?.daysRemaining },
              { id: 'recurring', label: 'Abonnements', icon: Calendar, color: 'purple', badge: recurringCount > 0 ? recurringCount : undefined },
              { id: 'alerts', label: 'Alertes', icon: AlertTriangle, color: 'orange', badge: alertsCount > 0 ? alertsCount : undefined },
            ].map((item) => (
              <button
                key={item.id}
                onClick={() => setViewMode(item.id as ViewMode)}
                className={`relative flex-1 p-2 rounded-lg transition-all ${
                  viewMode === item.id ? `bg-${item.color}-500/20 border border-${item.color}-500/40` : 'bg-white/5 border border-white/10'
                }`}
              >
                <div className="flex flex-col items-center gap-1">
                  <item.icon className={`w-4 h-4 ${viewMode === item.id ? `text-${item.color}-400` : 'text-white/60'}`} />
                  <span className={`text-[10px] ${viewMode === item.id ? 'text-white' : 'text-white/50'}`}>{item.label.split(' ')[0]}</span>
                </div>
                {item.badge !== undefined && (
                  <div className={`absolute -top-1 -right-1 min-w-[18px] h-[18px] px-1 rounded-full bg-${item.color}-500 border border-black flex items-center justify-center text-[10px] text-white font-medium`}>
                    {item.badge}
                  </div>
                )}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* CONTENU DYNAMIQUE */}
      <div className="flex-1 overflow-hidden">
        <AnimatePresence mode="wait">
          <motion.div
            key={viewMode}
            className="h-full overflow-y-auto scrollbar-thin p-5 space-y-4"
            initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}
          >
            {/* VUE GLOBALE - AVEC SÉPARATEURS */}
            {viewMode === 'all' && (
              <>
                {!projectionData ? <InsightSkeleton /> : (
                  <ProjectionCard projection={projectionData} transactions={recentTransactions} onShowDetails={() => setShowProjectionDetails(true)} />
                )}

                {recurringData?.patterns.some((p: any) => p.isActive) && (
                  <>
                    <div className="flex items-center gap-2 py-2">
                      <div className="h-px flex-1 bg-gradient-to-r from-transparent via-white/10 to-transparent" />
                      <span className="text-[10px] text-white/30 uppercase tracking-wider">Engagements</span>
                      <div className="h-px flex-1 bg-gradient-to-r from-transparent via-white/10 to-transparent" />
                    </div>
                    <RecurringCard 
                      recurring={recurringData} 
                      existingPeople={people} 
                      onFilterByRecurring={onFilterByRecurring}
                      onCreateRelation={handleCreateRelationFromPattern}
                    />
                  </>
                )}

                {(anomaliesData?.suspiciousCount > 0 || ruleViolations.length > 0) && (
                  <>
                    <div className="flex items-center gap-2 py-2">
                      <div className="h-px flex-1 bg-gradient-to-r from-transparent via-white/10 to-transparent" />
                      <span className="text-[10px] text-white/30 uppercase tracking-wider">Alertes</span>
                      <div className="h-px flex-1 bg-gradient-to-r from-transparent via-white/10 to-transparent" />
                    </div>
                    {anomaliesData && <AnomaliesCard anomalies={anomaliesData} onFilterByAnomaly={onFilterByAnomaly} />}
                    {violationsLoaded && <ViolationsCard violations={ruleViolations} onFilterByTransaction={onFilterByTransaction} />}
                  </>
                )}

                {/* État vide si tout est parfait */}
                {projectionData && !recurringCount && !alertsCount && (
                   <div className="flex flex-col items-center justify-center py-12 text-center">
                    <div className="w-16 h-16 rounded-full bg-green-500/20 flex items-center justify-center mb-4 border border-green-500/30">
                      <Sparkles className="w-8 h-8 text-green-400" />
                    </div>
                    <p className="text-sm text-white/80">Tout est optimal !</p>
                  </div>
                )}
              </>
            )}

            {/* VUE PROJECTION */}
            {viewMode === 'projection' && (
              !projectionData ? <InsightSkeleton /> : <ProjectionCard projection={projectionData} transactions={recentTransactions} onShowDetails={() => setShowProjectionDetails(true)} />
            )}

            {/* VUE RÉCURRENCES */}
            {viewMode === 'recurring' && (
              !recurringData ? <InsightSkeleton /> : (
                <RecurringCard 
                  recurring={recurringData} 
                  existingPeople={people} 
                  onFilterByRecurring={onFilterByRecurring} 
                  onCreateRelation={handleCreateRelationFromPattern}
                />
              )
            )}

            {/* VUE ALERTES */}
            {viewMode === 'alerts' && (
              <>
                {!anomaliesData || !violationsLoaded ? <><InsightSkeleton/><InsightSkeleton/></> : (
                  <>
                    <AnomaliesCard anomalies={anomaliesData} onFilterByAnomaly={onFilterByAnomaly} />
                    <ViolationsCard violations={ruleViolations} onFilterByTransaction={onFilterByTransaction} />
                  </>
                )}
              </>
            )}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
});
